### ISSUE TITLE
Add code of conduct

### ISSUE THREAD

**Issue by wikimatze** [vimberlin/vimberlin.de#26]
Content should be a simple "be excellent to each other!" and put it into the footer.

**Comment by schmidt** [comment]
Why not just adopt the [berlin code of conduct](http://berlincodeofconduct.org/) an be good with it? This should be more reliable than introducing a general "we're all nice" claim, that would not help in case of an actual incident.

**Comment by carpodaster** [comment]
:+1: to what @schmidt just wrote (you beat me to it by mere seconds :) )

**Comment by lucapette** [comment]
Not very active lately in vim berlin... sorry about that. But I was about to suggest the very same as @schmidt !

**Comment by wikimatze** [comment]
Thanks for your responses, we will discuss it on our next meetup.

**Comment by carpodaster** [comment]
Just a close, no explanation / summary?
